% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Project},
  pdfauthor={Maureen Renaud},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Project}
\author{Maureen Renaud}
\date{April 24, 2019}

\begin{document}
\maketitle

\#\#Comparing Performance By Grade In Girls' High School Cross-Country

\hypertarget{justification}{%
\subsubsection{Justification}\label{justification}}

As a long-time competitive distance runner, I have always been
interested in running related statistics. So for my project, I am going
to analyze the Illinois Girls' Cross-Country State Meet results. In
particular, I am going to look at the average place and time of the
participants competing at each grade level.

\hypertarget{why-illinois}{%
\paragraph{Why Illinois}\label{why-illinois}}

I chose Illinois because I grew up there and so am familiar with the
state meet structure, course, and environment.\\
Also, I know that the Illinois State High School Association
(www.ihsa.org) maintains a large amount of historical data and past
results, making it easy to find the necessary data for this project.

\hypertarget{why-girls}{%
\paragraph{Why Girls}\label{why-girls}}

I chose to focus on girls, because usually male runners show a more
typical pattern of improvement and gradually become faster as they age
from freshman to seniors. Female runners are not so straight-forward and
it is not unusual for a stellar freshman athlete to become a mediocre
senior. This occurs for a variety of reasons including onset of puberty,
weight gain, loss of interest, and injury. By taking an analytical look
at the data, I hope to see if there truly are significant differences in
performance as the girls age.

\hypertarget{data}{%
\subsubsection{Data}\label{data}}

For this project, I will be looking at the Illinois High School
Association Girls' State Cross-Country Meet results from 2007-2018. I
obtained my data from the Illinois High School Association's website
(www.ihsa.org), which has results of the state meet going back to the
mid-90s. I copied the results from each year and pasted each one into a
text document. I then saved all of those files to one .csv file. After
cleaning the format up, which took approximately 30-40 minutes for each
text document, I loaded the files into R.\\
I will only be pulling results from 2007- 2018. Prior to 2007, schools
competing in cross-country were divided into two classes, A or AA,
depending on enrollment size. Starting in 2007, schools were divided
into three classes, and AAA was added. I will focus on the years after
2007, to maintain consistency in the data that I am looking at. Another
factor that I needed to be aware of was the fact that the competition
distance for girls increased from 2.5 miles to 3.0 miles in 2002.
Fortunately, this will not cause an issue since I will not be looking at
data prior to the switch in distance. Finally, I will also be focusing
only on the 3A division. This is the biggest division out of the three
competing classes and I feel it would be most representative of the
population. This is because smaller schools often don't have as much
competition for varsity slots on their teams. So, the results could be
skewed because at a small school, an athlete might make the varsity team
and earn the opportunity to compete at state, solely because they joined
the team and not because of their athletic ability.

\hypertarget{variables}{%
\paragraph{Variables}\label{variables}}

For this project, I decided to look at place and time of the
participants at each grade level. I chose to focus on place because I
feel that is a good consistent measure of performance. Time is also
relevant. However, time can be extraordinarily variable in cross-country
due to changing course conditions and weather.

\hypertarget{demonstration}{%
\subsubsection{Demonstration}\label{demonstration}}

First, I will read in my data. This .csv file contains the results from
2007-2018.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{XCData <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\StringTok{"XCData.csv"}\NormalTok{,}\DataTypeTok{comm=}\StringTok{"#"}\NormalTok{,}\DataTypeTok{header=}\OtherTok{TRUE}\NormalTok{,}\DataTypeTok{sep=}\StringTok{","}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

I installed the lubridata package to ensure that my race times were
stored as durations in minutes and seconds. So, I will now ensure that
my time column is in the proper format. My time data is in the third
column, so I will apply the formatting to that column:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{XCData[,}\DecValTok{3}\NormalTok{] <-}\StringTok{ }\KeywordTok{as.duration}\NormalTok{(}\KeywordTok{ms}\NormalTok{(XCData[,}\DecValTok{3}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

Now I will take a look at a summary of my data:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(XCData)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Place           Grade          Time                                   
##  Min.   :  1.0   Sr     :468   Min.   :954s (~15.9 minutes)                
##  1st Qu.: 52.0   Jr     :419   1st Qu.:1074s (~17.9 minutes)               
##  Median :104.0   So     :340   Median :1105s (~18.42 minutes)              
##  Mean   :104.3   Fr     :249   Mean   :1107.77551349174s (~18.46 minutes)  
##  3rd Qu.:156.0   Jr     :178   3rd Qu.:1138s (~18.97 minutes)              
##  Max.   :217.0   Sr     :175   Max.   :1328s (~22.13 minutes)              
##                  (Other):654                                               
##       Year     
##  Min.   :2007  
##  1st Qu.:2010  
##  Median :2013  
##  Mean   :2013  
##  3rd Qu.:2016  
##  Max.   :2018  
## 
\end{verbatim}

I see that there are multiple factors for each grade level. So, I will
go ahead and combine those levels and put them in the traditional order
of Freshman, Sophomore, Junior, and Senior. I will also change year into
factor and then I will take another look at the summary to make sure
everything is cleaned up properly:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{levels}\NormalTok{(XCData}\OperatorTok{$}\NormalTok{Grade)<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Fr"}\NormalTok{, }\StringTok{"Fr"}\NormalTok{, }\StringTok{"Fr"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"Sr"}\NormalTok{, }\StringTok{"Sr"}\NormalTok{, }\StringTok{"Sr"}\NormalTok{)}
\NormalTok{XCData}\OperatorTok{$}\NormalTok{Grade <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(XCData}\OperatorTok{$}\NormalTok{Grade, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Fr"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"Sr"}\NormalTok{))}
\NormalTok{XCData}\OperatorTok{$}\NormalTok{Year <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(XCData}\OperatorTok{$}\NormalTok{Year)}
\KeywordTok{summary}\NormalTok{(XCData)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Place       Grade         Time                                   
##  Min.   :  1.0   Fr:431   Min.   :954s (~15.9 minutes)                
##  1st Qu.: 52.0   So:581   1st Qu.:1074s (~17.9 minutes)               
##  Median :104.0   Jr:701   Median :1105s (~18.42 minutes)              
##  Mean   :104.3   Sr:770   Mean   :1107.77551349174s (~18.46 minutes)  
##  3rd Qu.:156.0            3rd Qu.:1138s (~18.97 minutes)              
##  Max.   :217.0            Max.   :1328s (~22.13 minutes)              
##                                                                       
##       Year     
##  2015   : 217  
##  2011   : 216  
##  2008   : 210  
##  2009   : 210  
##  2016   : 210  
##  2017   : 210  
##  (Other):1210
\end{verbatim}

Now that the data is ready to go, I am going to use the aggregate
function to see what the mean time and place was by grade:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{placeaverage =}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ XCData[, }\DecValTok{1}\NormalTok{], }\DataTypeTok{by =} \KeywordTok{list}\NormalTok{(XCData}\OperatorTok{$}\NormalTok{Grade), }\DataTypeTok{FUN =}\NormalTok{ mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{placeaverage}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Group.1        x
## 1      Fr 110.8051
## 2      So 101.0740
## 3      Jr 104.1641
## 4      Sr 103.2260
\end{verbatim}

Just looking at numbers, it looks like Sophomores had the overall best
average place, followed by Seniors, then Juniors, and finally Freshman.
Later on I will determine if these differences are siginificant or not.
Right now, I would like to create a boxplot with error bars for this
data. I already have the average places, so now I will add standard
error to that information and change the names of my columns:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{placeaverage2 <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(placeaverage, }\KeywordTok{aggregate}\NormalTok{(XCData[,}\DecValTok{1}\NormalTok{], }\DataTypeTok{by =} \KeywordTok{list}\NormalTok{(XCData}\OperatorTok{$}\NormalTok{Grade), }\ControlFlowTok{function}\NormalTok{(x) (}\KeywordTok{sd}\NormalTok{(x, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)}\OperatorTok{/}\NormalTok{((}\KeywordTok{length}\NormalTok{(x) }\OperatorTok{-}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(x)))}\OperatorTok{^}\FloatTok{0.5}\NormalTok{))))[,}\OperatorTok{-}\DecValTok{3}\NormalTok{]}
\KeywordTok{names}\NormalTok{(placeaverage2) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Grade"}\NormalTok{, }\StringTok{"AvePlace"}\NormalTok{, }\StringTok{"PlaceSE"}\NormalTok{)}
\NormalTok{placeaverage2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Grade AvePlace  PlaceSE
## 1    Fr 110.8051 2.790345
## 2    So 101.0740 2.473015
## 3    Jr 104.1641 2.306060
## 4    Sr 103.2260 2.216012
\end{verbatim}

And now I can create my plot:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\FloatTok{4.1}\NormalTok{, }\FloatTok{4.1}\NormalTok{, }\FloatTok{0.6}\NormalTok{, }\FloatTok{0.6}\NormalTok{))}
\NormalTok{placeplot <-}\StringTok{ }\KeywordTok{with}\NormalTok{(placeaverage2, }\KeywordTok{barplot}\NormalTok{(AvePlace, }\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{max}\NormalTok{(AvePlace }\OperatorTok{+}\StringTok{ }\DecValTok{4}\OperatorTok{*}\NormalTok{PlaceSE)), }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"Orange"}\NormalTok{, }\StringTok{"Green"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{, }\StringTok{"Red"}\NormalTok{), }\DataTypeTok{ylab =} \StringTok{"Average Place"}\NormalTok{))}
\KeywordTok{with}\NormalTok{(placeaverage2, }\KeywordTok{arrows}\NormalTok{(placeplot, AvePlace }\OperatorTok{+}\StringTok{ }\NormalTok{PlaceSE, placeplot, AvePlace }\OperatorTok{-}\StringTok{ }\NormalTok{PlaceSE, }\DataTypeTok{length =} \FloatTok{0.05}\NormalTok{, }\DataTypeTok{angle =} \DecValTok{90}\NormalTok{, }\DataTypeTok{code =} \DecValTok{3}\NormalTok{))}
\KeywordTok{legend}\NormalTok{(}\StringTok{"topright"}\NormalTok{, }\DataTypeTok{inset =} \FloatTok{0.02}\NormalTok{, }\DataTypeTok{legend =} \KeywordTok{c}\NormalTok{(}\StringTok{"Fr"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"Sr"}\NormalTok{), }\DataTypeTok{fill =} \KeywordTok{c}\NormalTok{(}\StringTok{"Orange"}\NormalTok{, }\StringTok{"Green"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{, }\StringTok{"Red"}\NormalTok{), }\DataTypeTok{bg =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{cex =} \FloatTok{0.9}\NormalTok{) }\CommentTok{# legend}
\KeywordTok{axis}\NormalTok{(}\DataTypeTok{side =} \DecValTok{1}\NormalTok{, }\DataTypeTok{at =}\NormalTok{ placeplot[}\KeywordTok{c}\NormalTok{(}\FloatTok{1.5}\NormalTok{, }\FloatTok{2.5}\NormalTok{, }\FloatTok{3.5}\NormalTok{, }\FloatTok{4.5}\NormalTok{)], }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Fr"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"Sr"}\NormalTok{), }\DataTypeTok{tick =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{cex.axis =} \FloatTok{1.3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project_files/figure-latex/unnamed-chunk-9-1.pdf}

You can see that these are fairly similar and there may not be any
statistically significant difference between these groups. I will take a
quick look at a box plot to see if there are any big differences there:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(Place }\OperatorTok{~}\StringTok{ }\NormalTok{Grade, }\DataTypeTok{data =}\NormalTok{ XCData)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project_files/figure-latex/unnamed-chunk-10-1.pdf}

These are still very similar as well. You can see a visual difference in
the median performance for freshman but it is hard to differentiate the
other grades. I will be taking a closer look at some statistical
analysis, but first, I want to look at average time:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timeaverage =}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ XCData[, }\DecValTok{3}\NormalTok{], }\DataTypeTok{by =} \KeywordTok{list}\NormalTok{(XCData}\OperatorTok{$}\NormalTok{Grade), }\DataTypeTok{FUN =}\NormalTok{ mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{timeaverage}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Group.1        x
## 1      Fr 1112.504
## 2      So 1105.047
## 3      Jr 1108.360
## 4      Sr 1106.655
\end{verbatim}

I see that average times follow a similar pattern to places: Sophomores
ran the fastest, followed by Seniors, Juniors, and then Freshmen. I woud
like to create a plot for the times as well. I already have my mean
times. So, now I need to find the standard deviation:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timeaverage2 <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(timeaverage, }\KeywordTok{aggregate}\NormalTok{(XCData[,}\DecValTok{3}\NormalTok{], }\DataTypeTok{by =} \KeywordTok{list}\NormalTok{(XCData}\OperatorTok{$}\NormalTok{Grade), }\ControlFlowTok{function}\NormalTok{(x) (}\KeywordTok{sd}\NormalTok{(x, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)}\OperatorTok{/}\NormalTok{((}\KeywordTok{length}\NormalTok{(x) }\OperatorTok{-}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(x)))}\OperatorTok{^}\FloatTok{0.5}\NormalTok{))))[,}\OperatorTok{-}\DecValTok{3}\NormalTok{]}
\KeywordTok{names}\NormalTok{(timeaverage2) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Grade"}\NormalTok{, }\StringTok{"AveTime"}\NormalTok{, }\StringTok{"TimeSE"}\NormalTok{) }\CommentTok{#This changes the names of the columns}
\NormalTok{timeaverage2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Grade  AveTime   TimeSE
## 1    Fr 1112.504 2.287986
## 2    So 1105.047 2.130534
## 3    Jr 1108.360 2.014314
## 4    Sr 1106.655 1.966264
\end{verbatim}

And now here is my plot:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\FloatTok{4.1}\NormalTok{, }\FloatTok{4.1}\NormalTok{, }\FloatTok{0.6}\NormalTok{, }\FloatTok{0.6}\NormalTok{))}
\NormalTok{timeplot <-}\StringTok{ }\KeywordTok{with}\NormalTok{(timeaverage2, }\KeywordTok{barplot}\NormalTok{(AveTime, }\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{max}\NormalTok{(AveTime }\OperatorTok{+}\StringTok{ }\DecValTok{10}\OperatorTok{*}\NormalTok{TimeSE)), }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"Orange"}\NormalTok{, }\StringTok{"Green"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{, }\StringTok{"Red"}\NormalTok{), }\DataTypeTok{ylab =} \StringTok{"Average Time (s)"}\NormalTok{))}
\KeywordTok{with}\NormalTok{(timeaverage2, }\KeywordTok{arrows}\NormalTok{(timeplot, AveTime }\OperatorTok{+}\StringTok{ }\NormalTok{TimeSE, timeplot, AveTime }\OperatorTok{-}\StringTok{ }\NormalTok{TimeSE, }\DataTypeTok{length =} \FloatTok{0.05}\NormalTok{, }\DataTypeTok{angle =} \DecValTok{90}\NormalTok{, }\DataTypeTok{code =} \DecValTok{3}\NormalTok{))}
\KeywordTok{legend}\NormalTok{(}\StringTok{"topright"}\NormalTok{, }\DataTypeTok{inset =} \FloatTok{0.02}\NormalTok{, }\DataTypeTok{legend =} \KeywordTok{c}\NormalTok{(}\StringTok{"Fr"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"Sr"}\NormalTok{), }\DataTypeTok{fill =} \KeywordTok{c}\NormalTok{(}\StringTok{"Orange"}\NormalTok{, }\StringTok{"Green"}\NormalTok{, }\StringTok{"Blue"}\NormalTok{, }\StringTok{"Red"}\NormalTok{), }\DataTypeTok{bg =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{cex =} \FloatTok{0.9}\NormalTok{) }\CommentTok{# legend}
\KeywordTok{axis}\NormalTok{(}\DataTypeTok{side =} \DecValTok{1}\NormalTok{, }\DataTypeTok{at =}\NormalTok{ timeplot[}\KeywordTok{c}\NormalTok{(}\FloatTok{1.5}\NormalTok{, }\FloatTok{2.5}\NormalTok{, }\FloatTok{3.5}\NormalTok{, }\FloatTok{4.5}\NormalTok{)], }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Fr"}\NormalTok{, }\StringTok{"So"}\NormalTok{, }\StringTok{"Jr"}\NormalTok{, }\StringTok{"Sr"}\NormalTok{), }\DataTypeTok{tick =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{cex.axis =} \FloatTok{1.3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project_files/figure-latex/unnamed-chunk-13-1.pdf}

Looking at the chart, it appears that there is no siginficant difference
when it comes to average time among the grades. Even my error bars were
hardly a blip on the plot. I will take a look at a barplot to see if I
can see any differentiation between the groups:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(Time }\OperatorTok{~}\StringTok{ }\NormalTok{Grade, }\DataTypeTok{data =}\NormalTok{ XCData)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project_files/figure-latex/unnamed-chunk-14-1.pdf}

Looking at this, you can see that they are still very similar. Though, a
big difference I see is that the ``older'' grades have more outliers on
the slower side. Now, I would actually like to run the statistical tests
to confirm what I believe these plots already indicate: that there is no
statistically significant difference in performance among the grades.

First, I will use lm() to fit a linear model:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LinearPlace <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(Place }\OperatorTok{~}\StringTok{ }\NormalTok{Grade, }\DataTypeTok{data =}\NormalTok{ XCData)}
\KeywordTok{summary}\NormalTok{(LinearPlace)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Place ~ Grade, data = XCData)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -109.805  -52.164   -0.074   51.350  113.774 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  110.805      2.906  38.133   <2e-16 ***
## GradeSo       -9.731      3.835  -2.537   0.0112 *  
## GradeJr       -6.641      3.692  -1.799   0.0722 .  
## GradeSr       -7.579      3.629  -2.089   0.0369 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 60.32 on 2479 degrees of freedom
## Multiple R-squared:  0.002784,   Adjusted R-squared:  0.001577 
## F-statistic: 2.307 on 3 and 2479 DF,  p-value: 0.07473
\end{verbatim}

The coefficient for the Intercept is the mean place for the first level
of the factor variable (which in this case is Freshmen). The coefficient
for GradeSo is the difference in mean place between Freshmen and
Sophomores. The coefficient for GradeJr is the difference in mean place
between Freshmen and Juniors. The coefficient for Grade Sr.~is the
difference in mean place between Freshmen and Seniors. Though we already
knew that information from calculating the means for each group.

I will now run an ANOVA on this model to get my analysis of variance
table:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{anova}\NormalTok{(LinearPlace)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Place
##             Df  Sum Sq Mean Sq F value  Pr(>F)  
## Grade        3   25186  8395.3   2.307 0.07473 .
## Residuals 2479 9021166  3639.0                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Looking at my p-value of 0.07, it appears that at a 95\% significance
level there is no statistically significant difference in place based on
grade. However, to take a closer look at individual groups, I will run
an ANOVA with a Tukey test.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{TukeyHSD}\NormalTok{(}\KeywordTok{aov}\NormalTok{(Place }\OperatorTok{~}\StringTok{ }\NormalTok{Grade, }\DataTypeTok{data =}\NormalTok{ XCData))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Place ~ Grade, data = XCData)
## 
## $Grade
##             diff        lwr        upr     p adj
## So-Fr -9.7310941 -19.589818  0.1276295 0.0545741
## Jr-Fr -6.6410531 -16.133599  2.8514928 0.2742272
## Sr-Fr -7.5791304 -16.908335  1.7500747 0.1570821
## Jr-So  3.0900410  -5.610656 11.7907385 0.7979196
## Sr-So  2.1519637  -6.370230 10.6741570 0.9158722
## Sr-Jr -0.9380773  -9.033865  7.1577101 0.9908135
\end{verbatim}

Looking at the results, I see that at a 95\% significance level, there
is no statistically significant difference between any of the groups.
The p-value comparing the Sophomores and Freshman was nearly
significant, but still missed the mark. This makes sense because looking
at the average place, Freshman on average placed the lowest (at 110) and
Sophomores placed the highest (at 103).

Now, I will run the same tests looking at Time. First, I will use lm()
to fit a linear model:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LinearTime <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(Time }\OperatorTok{~}\StringTok{ }\NormalTok{Grade, }\DataTypeTok{data =}\NormalTok{ XCData)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Note: method with signature 'Duration#ANY' chosen for function '-',
##  target signature 'Duration#Duration'.
##  "ANY#Duration" would also be valid
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(LinearTime)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Time ~ Grade, data = XCData)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -152.66  -34.50   -2.36   30.64  219.64 
## attr(,"class")
## [1] "Duration"
## attr(,"class")attr(,"package")
## [1] "lubridate"
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 1112.504      2.519 441.633   <2e-16 ***
## GradeSo       -7.457      3.325  -2.243   0.0250 *  
## GradeJr       -4.144      3.201  -1.295   0.1956    
## GradeSr       -5.848      3.146  -1.859   0.0631 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 52.3 on 2479 degrees of freedom
## Multiple R-squared:  0.002232,   Adjusted R-squared:  0.001025 
## F-statistic: 1.849 on 3 and 2479 DF,  p-value: 0.1362
\end{verbatim}

The coefficient for the Intercept is the mean time in seconds for the
first level of the factor variable (which in this case is Freshmen). The
coefficient for GradeSo is the difference in mean time between Freshmen
and Sophomores. The coefficient for GradeJr is the difference in mean
time between Freshmen and Juniors. The coefficient for Grade Sr.~is the
difference in mean time between Freshmen and Seniors. Though, once
again, we already knew that information from calculating the mean times
for each group.

I will now run an ANOVA on this model to get my analysis of variance
table:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{anova}\NormalTok{(LinearTime)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Time
##             Df  Sum Sq Mean Sq F value Pr(>F)
## Grade        3   15167  5055.8  1.8485 0.1362
## Residuals 2479 6780077  2735.0
\end{verbatim}

With a p-value of 0.1362, it does not appear that at a 95\% significance
level there is a stastistically significant difference in time between
grades. Though, based on my bar plots, I already expected that result. I
will go ahead and run a Tukey test to take a closer look at the
difference between groups.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{TukeyHSD}\NormalTok{(}\KeywordTok{aov}\NormalTok{(Time }\OperatorTok{~}\StringTok{ }\NormalTok{Grade, }\DataTypeTok{data =}\NormalTok{ XCData))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Time ~ Grade, data = XCData)
## 
## $Grade
##            diff        lwr       upr     p adj
## So-Fr -7.456956 -16.003818  1.089905 0.1121030
## Jr-Fr -4.143887 -12.373297  4.085523 0.5665031
## Sr-Fr -5.848490 -13.936294  2.239314 0.2461905
## Jr-So  3.313069  -4.229861 10.855999 0.6715120
## Sr-So  1.608467  -5.779712  8.996645 0.9439178
## Sr-Jr -1.704603  -8.723115  5.313910 0.9242817
\end{verbatim}

As we already knew, at a 95\% significance level, there is no
significant difference between any of the groups. The closest we came to
a significant difference was once again between the Freshman and
Sophomores. However, it was further from being significant than
evaluating the groups based on Place.

\hypertarget{overall-thoughts}{%
\subsubsection{Overall Thoughts}\label{overall-thoughts}}

In my introduction, I implied that that it would be unlikely that we
would see a consistent pattern of improvment from Freshman, to
Sophomore, to Junior, to Senior year. However, I honestly wasn't
expecting to see that there was no statistical difference at all
comparing the performance at each grade level.

\hypertarget{looking-forward}{%
\subsubsection{Looking Forward}\label{looking-forward}}

In my introduction, I stated that I chose to focus on girls because I
knew that it would be unlikely that we would see a consistent pattern of
impovment from Freshman to Senior year. I hypothesized that boys would
show that more traditional pattern of improvement. So, if I had time I
would have liked to run these same analyses on the boys results. (My
primary road block to this is just the amount of time it takes to clean
this data up. I probably spent 7-8 hours preparing the girls data.)

I could also look at my data based on year. That could potentially be
interesting because I could see how the data would evolve if there were
a particularly strong class (say if the Class of 2015 consistently
outperformed other classes regardless of their year in school.)

Another addition to this study would be to run these tests on the other
divisions (A and AA). It would be interesting to see if school size
truly did impact the students that earned the right to compete at the
State meet.

\end{document}
